modules/components/org.wso2.carbon.stream.processor.core/pom.xml, modules/components/org.wso2.carbon.stream.processor.core/src/main/java/org/wso2/streamprocessor/core/StreamProcessorService.java, modules/features/org.wso2.carbon.stream.processor.core.feature/pom.xml, pom.xml
also removing  siddhiManager.setExtension("outputmapper:text", PassThroughOutputMapper.class); temporary fix
=> Adding kafka subscribers and publishers and Text input and output mappers

modules/samples/artifacts/0041/README.txt, modules/samples/artifacts/0041/rabbitmq-sample.siddhi
Adding sample for siddhi-io-rabbitmq
=> Sample for siddhi-io-rabbitmq

modules/distribution/pom.xml, modules/samples/artifacts/0042/README.txt, modules/samples/artifacts/0042/mqtt-sample.siddhi, pom.xml
Adding samples  for siddhi-io-mqtt and adding changes in product sp pom.xml
=> Adding sample for siddhi-io-mqtt

modules/distribution/pom.xml, pom.xml
=> changes in product sp pom

modules/samples/artifacts/0040/EmailSinkSiddhiAppTest.siddhi, modules/samples/artifacts/0040/README
=> Adding sample 40 for email io

modules/distribution/carbon-home/bin/dashboard.bat, modules/distribution/carbon-home/bin/dashboard.sh, modules/distribution/carbon-home/conf/deployment.yaml, modules/distribution/pom.xml, pom.xml
This PR adds Dashboard runtime to SP product.
Following features are introduced in this PR:
- org.wso2.carbon.dashboards.api.feature
- org.wso2.carbon.dashboards.portal.feature
- org.wso2.carbon.uis.core.feature
=> Add Dashboard features and runtime

modules/distribution/pom.xml, modules/samples/artifacts/0046/README, modules/samples/artifacts/0046/UnitConversionForCentimetreToFootSiddhiAppTest.siddhi, pom.xml
- Added Sample for siddhi-execution-unitconversion
- siddhi-execution-unitconversion jar packed with product
=> Added Unit Conversion Extension Samples

modules/distribution/carbon-home/conf/dashboard/deployment.yaml
- Adding dashboard related configurations ( changes of #59 by @lasanthaS)
=> Kernel Migration Phase 16

modules/samples/artifacts/0009/README.txt
Improved with the prerequisite steps such as installing and creating user access rights in MongoDB.
Fix for : https://github.com/wso2/product-sp/issues/80
=> Improved 0009 - MongoDB sample

modules/samples/artifacts/0044/steaming-kmeans-incremental-sample.siddhi, modules/samples/artifacts/0044/steaming-kmeans-minibatch-sample.siddhi
kmeans syntax is changed in https://github.com/wso2-extensions/siddhi-execution-streamingml/pull/40
=> sample query changed

modules/distribution/pom.xml, pom.xml
Change the siddhi version to 4.0.0-M89.
Update the versions of siddhi-execution extensions
Add siddhi-store-hbase extension artifact to the product.
=> Update versions of siddhi and execution extensions.

modules/samples/artifacts/0050/README.txt, modules/samples/artifacts/0050/hbase-store-test-plan.siddhi
Please merge ONCE the HBase store implementation has been released and added to the pack.
=> Add sample for the HBase store extension

pom.xml
msf4j is migrated to v2.4.1 version.
Update other dependencies according to msf4j changes. 
Bumped carbon analytic and siddhi versions.
=> Update the dependencies in pom file 

pom.xml
This PR updates versions of following dependent components.
- carbon-dashboards (4.0.0.m10)
- carbon-ui-server (0.10.14)
=> Update carbon-dashboard/ui-server versions

modules/samples/artifacts/0040/EmailSinkSiddhiAppTest.siddhi, modules/samples/artifacts/0040/EmailSourceSiddhiAppTest.siddhi, modules/samples/artifacts/0040/README.txt
> Improve the siddhi-io-email extension sample.
> Edit email sink and source siddhi app so that event send by email sink to the email account and get them back using email source.
=> Improve the sample

modules/distribution/pom.xml, modules/integration/pom.xml, modules/integration/test-results-service/pom.xml, modules/integration/tests-kubernetes-integration/pom.xml, modules/samples/sample-clients/http-client/pom.xml, modules/samples/sample-clients/http-server/pom.xml, modules/samples/sample-clients/kafka-consumer/pom.xml, modules/samples/sample-clients/kafka-producer/pom.xml, modules/samples/sample-clients/pom.xml, modules/samples/sample-clients/tcp-client/pom.xml, modules/samples/sample-clients/tcp-server/pom.xml, modules/samples/sample-clients/wso2event-client/pom.xml, modules/samples/sample-clients/wso2event-server/pom.xml, modules/tests/pom.xml, pom.xml
> Refactoring version with M15.
> Fixing release build issue.
=> Refactoring version with M15-SNAPSHOT.

pom.xml
> Bump Siddhi, Carbon Analytics, map-extension, and io-extension versions
> Adding the latest dependencies for Product-SP
=> Bumped Siddhi, Carbon Analytics, map-extension, and io-extension versions

pom.xml
> Remove the SNAPSHOT version of carbon analytic
> Remove the SNAPSHOT version of carbon analytic
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
=> Fix carbon-analytic dependency

pom.xml
> Updated the carbon-analytics dependency version.
=> Updating the carbon-analytics version.

modules/distribution/carbon-home/bin/editor.sh, modules/distribution/carbon-home/bin/worker.sh
This pull request fixes the issue #110
worker and editor should be able to start, stop, restart in nohup mode
=> worker and editor dont start properly with nohup mode

modules/distribution/carbon-home/conf/editor/deployment.yaml, modules/distribution/carbon-home/conf/worker/deployment.yaml, pom.xml
> Use the latest carbon-coordination version
> To use the new configuration name refactoring of hearbeatMaxRetry
=> Updated Carbon Coordination Version

modules/samples/artifacts/1003/AggregateOverTime.siddhi, modules/samples/artifacts/1004/DataPreprocessing.siddhi, modules/samples/artifacts/1006/HelloKafka.siddhi, modules/samples/artifacts/1007/OnlineLearning.siddhi, modules/samples/artifacts/1008/PatternMatching.siddhi
> Improvements to SP Editor samples
=> Improvements to SP Editor samples

modules/distribution/carbon-home/conf/dashboard/deployment.yaml, modules/distribution/carbon-home/conf/worker/deployment.yaml, modules/distribution/pom.xml, pom.xml
> Adding siddhi carbon metrics,  features and their configurations
=> Adding Metrics features

modules/samples/artifacts/1001/ReceiveAndCount.siddhi, modules/samples/artifacts/1006/HelloKafka.siddhi, modules/samples/artifacts/1007/OnlineLearning.siddhi, modules/samples/artifacts/1008/PatternMatching.siddhi
Improving the samples 1001, 1006, 1007 and 1008
=> Improving the samples 1001, 1006, 1007 and 1008

modules/samples/artifacts/1002/AlertsAndThresholds.siddhi, modules/samples/artifacts/1003/AggregateOverTime.siddhi, modules/samples/artifacts/1004/DataPreprocessing.siddhi, modules/samples/artifacts/1005/JoinWithStoredData.siddhi
> Improve the samples 1002, 1003, 1004, 1005
=> Improve the samples 1002, 1003, 1004, 1005

modules/distribution/carbon-home/conf/worker/deployment.yaml, pom.xml
> Bumped siddhi and extensions version. 
> Fixing deployment.yaml file issue.
=> Bumped siddhi and extensions version. 

pom.xml
> To pack latest dependencies with the product distribution.
=> Bumping the carbon-analytics and store-rdbms dependencies

pom.xml
> Bumped siddhi and carbon-analytics version.
=>  Bumped siddhi and carbon-analytics version. 

modules/distribution/pom.xml, pom.xml
> Adding Data Provider Feature.
=> Adding Data Provider Feature.

pom.xml
> Bump carbon analytics to latest version
=> Bump Carbon Analytics Version

modules/samples/sample-clients/http-client/src/main/java/org/wso2/sp/http/client/HttpClient.java, modules/samples/sample-clients/http-server/src/main/java/org/wso2/sp/http/server/HttpServerListenerHandler.java, modules/samples/sample-clients/http-server/src/main/java/org/wso2/sp/http/server/HttpServerMain.java, modules/samples/sample-clients/http-server/src/main/java/org/wso2/sp/http/server/HttpsServerListnerHandler.java, modules/samples/sample-clients/kafka-consumer/src/main/java/org/wso2/sp/sample/kafka/consumer/KafkaReceiver.java, modules/samples/sample-clients/kafka-producer/src/main/java/org/wso2/sp/sample/kafka/client/KafkaClient.java, modules/samples/sample-clients/tcp-client/src/main/java/org/wso2/sp/tcp/client/StoreTestClient.java, modules/samples/sample-clients/tcp-client/src/main/java/org/wso2/sp/tcp/client/TCPClient.java, modules/samples/sample-clients/wso2event-client/src/main/java/org/wso2/carbon/sample/wso2event/Client.java, modules/samples/sample-clients/wso2event-server/src/main/java/org/wso2/carbon/sample/server/DatabridgeTestServer.java
Improvements on sample clients
Set error free sample clients
N/A
N/A
N/A
N/A
N/A
N/A
N/A
- Unit tests 
N/A
N/A
N/A
N/A
N/A
N/A
N/A
=> Improvements on sample clients

modules/distribution/carbon-home/bin/dashboard.sh, modules/distribution/carbon-home/bin/editor.sh, modules/distribution/carbon-home/bin/manager.sh, modules/distribution/carbon-home/bin/worker.sh
> Fix for https://github.com/wso2/product-sp/issues/155
> Make SP run when SP_HOME contain white spaces.
=> Fix for https://github.com/wso2/product-sp/issues/155

modules/distribution/pom.xml, pom.xml
> Adding Distributed Resource feature to editor runtime
=> Adding Distributed Resource feature for editor runtime

pom.xml
> Update the dependencies versions for alpha2 release.
=> Update the dependencies versions.

modules/distribution/pom.xml, pom.xml
Adding the Store REST API to product-sp
Ability to query the tables in active siddhi apps
=> Adding Store/Table REST API

pom.xml
=> Bump RDBMS store version

modules/samples/artifacts/0031/README.txt, modules/samples/artifacts/0032/README.txt, modules/samples/artifacts/0034/README.txt, modules/samples/artifacts/0035/README.txt, modules/samples/artifacts/0039/README.txt, modules/samples/artifacts/0040/README.txt, modules/samples/artifacts/0043/README.txt, modules/samples/artifacts/0044/README.txt, modules/samples/artifacts/0045/README, modules/samples/artifacts/0046/README, modules/samples/artifacts/0047/README, modules/samples/artifacts/0048/README, modules/samples/artifacts/0051/README.txt, modules/samples/artifacts/0052/README.txt
Refactoring samples to include authentication. 
Changed the README sample with authentication.
=> README.txt edited

modules/distribution/carbon-home/conf/editor/deployment.yaml
Disabling interceptor in editor profile
=> Disabling interceptor in editor profile

modules/distribution/carbon-home/conf/manager/deployment.yaml, modules/distribution/carbon-home/conf/worker/deployment.yaml
> Adding sample configurations of distributed setups in deployment.yml
> Make it easy for user to configure distributed setups
> Added sample configs to deployment.yaml
=> Added samples for distributed.config in deployment.yaml

pom.xml
=> Bump HBase store version in SP pack

pom.xml
Bump version
- Ran FindSecurityBugs plugin and verified report? yes/no
=> Bump siddhi-io-file version

pom.xml
> Update the siddhi-map- dependencies versions.
=> Update the mappers dependencies versions.

pom.xml
Bumping siddhi-io-kafka version to 4.0.15
=> Bumping siddhi-io-kafka version to 4.0.15

modules/distribution/carbon-home/conf/dashboard/deployment.yaml, modules/samples/artifacts/0038/README.txt, modules/samples/artifacts/0038/siddhi-io-file-sample.siddhi
>
- Updating business rules manager configs in dashboard/deployment.yaml .
- Updating siddhi-io-file sample siddhi app. 
- Update readme for siddhi-io-file sample (0038).
=>  Updating business rules manager configs in dashboard/deployment.yaml 

modules/distribution/pom.xml, pom.xml
Bump analytics-common version to 6.0.16
=> Bump analytics-common version to 6.0.16

pom.xml
> Upgrade dashboards and UI server version
Carbon-UI-Server - 0.12.0
Carbon-dashboards - 4.0.0.beta
=> Upgrade dashboards and UI server version

pom.xml
Bump Siddhi version to 4.0.0-beta
=> Bump Siddhi version to 4.0.0-beta

modules/distribution/carbon-home/bin/dashboard/carbon.bat, modules/distribution/carbon-home/bin/dashboard/carbon.sh, modules/distribution/carbon-home/bin/editor/carbon.bat, modules/distribution/carbon-home/bin/editor/carbon.sh, modules/distribution/carbon-home/bin/manager/carbon.bat, modules/distribution/carbon-home/bin/manager/carbon.sh, modules/distribution/carbon-home/bin/worker/carbon.bat, modules/distribution/carbon-home/bin/worker/carbon.sh, modules/distribution/carbon-home/conf/transports/dashboard/netty-transports.yml, modules/distribution/carbon-home/conf/transports/editor/netty-transports.yml, modules/distribution/carbon-home/conf/transports/manager/netty-transports.yml, modules/distribution/carbon-home/conf/transports/worker/netty-transports.yml, modules/distribution/src/assembly/bin.xml
> Https trustStore and  keyStore added and adding  message processor ID
=> Enable HTTPS trustStore and keystore sys varible

modules/distribution/pom.xml, pom.xml
>  Changing dependency name from das to sp due to change in carbon-analytics
=>  Changing dependency name from das to sp due to change in carbon-analytics

modules/distribution/pom.xml, pom.xml
> carbon-analytics to version 2.0.182
> carbon-analytics-common to version 6.0.22
> carbon kernel to 5.2.2
=> Bump dependency versions

modules/distribution/src/assembly/filter.properties, pom.xml
=> Add version bumps

modules/distribution/carbon-home/conf/dashboard/log4j2.xml, modules/distribution/carbon-home/conf/editor/log4j2.xml, modules/distribution/carbon-home/conf/manager/log4j2.xml, modules/distribution/carbon-home/conf/worker/log4j2.xml
> Eliminating hikari pool info logs for all runtimes
> Adding custom log appender for editor runtime
=> Adding log4j2.xml files for runtimes

pom.xml
=> Bump carbon config version, fixes #163

modules/distribution/src/assembly/bin.xml
> $subject since copying the folder doesnt work when the same file comes from kernel
=> Copying log4j2.xml files individually for runtimes

pom.xml
=> Bumped coordination version

modules/distribution/carbon-home/conf/editor/deployment.yaml
Updating the auth configs for editor as per Issue https://github.com/wso2/carbon-analytics-common/pull/457 solution.
=> Updating the auth configs for editor as per Issue#460 solution

modules/distribution/pom.xml, pom.xml
> Change the data provider dependency group id.
=> Fix the data provider dependency.

modules/distribution/pom.xml, pom.xml
Reverting dataprovider, auth.rest.api and interceptor dependency changes
=> Reverting dataprovider, auth.rest.api and interceptor dependency changes

modules/distribution/carbon-home/conf/dashboard/deployment.yaml, modules/distribution/carbon-home/conf/editor/deployment.yaml, modules/distribution/carbon-home/conf/manager/deployment.yaml, modules/distribution/carbon-home/conf/worker/deployment.yaml
> Setting the default ports in deployment.yaml
=> Adding default ports for all runtimes

pom.xml
=> Bump carbon-analytics carbon-dashboards and io-http versions

pom.xml
=> Bump analytics-common version

modules/distribution/pom.xml, pom.xml
> owasp feature not used anymore. Dependency packed in editor core
=> Revert owasp feature

modules/samples/artifacts/PublishDataEventToFile/PublishDataEventToFile.siddhi, modules/samples/artifacts/PublishHTTPInJsonFormatWithCustomMapping/PublishHTTPInJsonFormatWithCustomMapping.siddhi, modules/samples/artifacts/PublishHttpInJsonFormat/PublishHttpInJsonFormat.siddhi, modules/samples/artifacts/PublishHttpInXmlFormat/PublishHttpInXmlFormat.siddhi, modules/samples/artifacts/PublishKafkaInBinaryFormat/PublishKafkaInBinaryFormat.siddhi, modules/samples/artifacts/PublishKafkaInJsonFormat/PublishKafkaInJsonFormat.siddhi, modules/samples/sample-clients/kafka-consumer/build.xml, modules/samples/sample-clients/kafka-consumer/pom.xml, modules/samples/sample-clients/kafka-consumer/src/main/java/org/wso2/sp/sample/kafka/consumer/KafkaReceiver.java
> To view the output on the kafka-server which were sent through kafka-server. It is a simple server written in siddhi.
=> Kafka Consumer to test sample

modules/samples/artifacts/PublishHttpInXmlFormatWithCustomMapping/PublishHttpInXmlFormatWithCustomMapping.siddhi, modules/samples/artifacts/PublishMqttInXmlFormat/PublishMqttInXmlFormat.siddhi, modules/samples/artifacts/PublishRabbitmqInXmlFormat/PublishRabbitmqInXmlFormat.siddhi, modules/samples/artifacts/PublishTcpInBinaryFormat/PublishTcpInBinaryFormat.siddhi, modules/samples/artifacts/PublishTcpInJsonFormat/PublishTcpInJsonFormat.siddhi, modules/samples/artifacts/PublishTcpInTextFormat/PublishTcpInTextFormat.siddhi, modules/samples/artifacts/PublishWSO2Event/PublishWSO2Event.siddhi, modules/samples/sample-clients/mqtt-consumer/build.xml, modules/samples/sample-clients/mqtt-consumer/pom.xml, modules/samples/sample-clients/mqtt-consumer/src/main/java/org/wso2/sp/sample/mqtt/consumer/MqttReceiver.java, modules/samples/sample-clients/pom.xml, modules/samples/sample-clients/tcp-server/build.xml, modules/samples/sample-clients/tcp-server/pom.xml, modules/samples/sample-clients/tcp-server/src/main/java/org/wso2/sp/tcp/server/TCPServer.java, pom.xml
To demonstrate how to publish events.
Samples for TCP, HTTP,RabbitMQ and MQTT with user documentation.
=> Adding producing samples 

modules/samples/sample-clients/rabbitmq-consumer/build.xml
> All the properties are added for user to determine parameters.
=> Optional properties are added and mentioned corrections.

modules/samples/sample-clients/mqtt-consumer/pom.xml
=> Fix for parent version in pom.xml

modules/samples/artifacts/ReceiveRabbitmqInJSONFormat/ReceiveRabbitmqInJSONFormat.siddhi, modules/samples/sample-clients/rabbitmq-producer/build.xml, modules/samples/sample-clients/rabbitmq-producer/pom.xml, modules/samples/sample-clients/rabbitmq-producer/src/main/java/org/wso2/sp/sample/rabbitmq/producer/RabbitMQProducer.java
To add sample producer for rabbitmq and rabbitmq sample in json format
=> Adding Rabbitmq producer and the sample in json format

modules/samples/artifacts/PublishKafkaInBinaryFormat/PublishKafkaInBinaryFormat.siddhi, modules/samples/artifacts/PublishKafkaInJsonFormat/PublishKafkaInJsonFormat.siddhi, modules/samples/artifacts/ReceiveHTTPInJsonFormatWithCustomMapping/ReceiveHTTPInJsonFormatWithCustomMapping.siddhi, modules/samples/artifacts/ReceiveHTTPInJsonFormatWithDefaultMapping/ReceiveHTTPInJsonFormatWithDefaultMapping.siddhi, modules/samples/artifacts/ReceiveHTTPInXMLFormatWithDefaultMapping/ReceiveHTTPInXMLFormatWithDefaultMapping.siddhi, modules/samples/artifacts/ReceiveHTTPinXMLFormatWithCustomMapping/ReceiveHTTPinXMLFormatWithCustomMapping.siddhi, modules/samples/artifacts/ReceiveKafkaInBinaryFormat/ReceiveKafkaInBinaryFormat.siddhi, modules/samples/artifacts/ReceiveTCPinBinaryFormat/ReceiveTCPinBinaryFormat.siddhi, modules/samples/artifacts/ReceiveTCPinJSONFormat/ReceiveTCPinJSONFormat.siddhi, modules/samples/artifacts/ReceiveTCPinTextFormat/ReceiveTCPinTextFormat.siddhi, modules/samples/sample-clients/kafka-producer/src/main/java/org/wso2/sp/sample/kafka/client/KafkaClient.java, modules/samples/sample-clients/rabbitmq-producer/pom.xml, modules/samples/sample-clients/rabbitmq-producer/src/main/java/org/wso2/sp/sample/rabbitmq/producer/RabbitMQProducer.java, pom.xml
=> Changes to samples and clients

modules/distribution/carbon-home/conf/dashboard/deployment.yaml, pom.xml
=> Update pom and update yml

pom.xml
=> Bump io file version

modules/distribution/carbon-home/conf/dashboard/deployment.yaml
> Remove optional config related to status dashboard
=> Remove optional config related to status dashboard

pom.xml
> Bump carbon-analytics version.
=> Bump carbon-analytics version.

modules/samples/artifacts/ReceiveRabbitmqInJSONFormat/ReceiveRabbitmqInJSONFormat.siddhi, modules/samples/sample-clients/http-client/src/main/java/org/wso2/sp/http/client/HttpClient.java, modules/samples/sample-clients/mqtt-client/src/main/java/org/wso2/sp/mqtt/client/MqttClient.java, modules/samples/sample-clients/rabbitmq-producer/build.xml, modules/samples/sample-clients/tcp-client/src/main/java/org/wso2/sp/tcp/client/TCPClient.java
=> Changes to sample clients and the rabbitmq sample

modules/samples/artifacts/PublishJmsInXmlFormat/PublishJmsInXmlFormat.siddhi
Correcting file name of the siddhi file PublishJmsXmlformat.siddhi. Since it works with xml.
=> Changed file name to PublishJmsInXmlformat.siddhi

modules/samples/sample-clients/jms-consumer/pom.xml, modules/samples/sample-clients/jms-producer/src/main/java/org/wso2/sp/sample/jms/client/JmsClient.java, modules/samples/sample-clients/kafka-consumer/pom.xml, modules/samples/sample-clients/pom.xml, modules/samples/sample-clients/rabbitmq-consumer/pom.xml, modules/samples/sample-clients/tcp-server/pom.xml, modules/samples/sample-clients/wso2event-client/pom.xml, modules/samples/sample-clients/wso2event-server/pom.xml
> Improve the JMS sample producer which can publish the key-value events for default 'SweetProductStream'.
> Add JMS sample producer  'key-value' support.
=> Add JMS sample producer  'keyvalue' support.

pom.xml
> Bump msf4j dependency version.
=> Bump msf4j dependency version.

pom.xml
=> Revert "Bump msf4j dependency version."

modules/samples/artifacts/1001/ReceiveAndCount.siddhi, modules/samples/sample-clients/http-client/build.xml, modules/samples/sample-clients/http-client/src/main/java/org/wso2/sp/http/client/EventSendingUtil.java, modules/samples/sample-clients/http-client/src/main/java/org/wso2/sp/http/client/HttpClient.java, modules/samples/sample-clients/kafka-producer/src/main/java/org/wso2/sp/sample/kafka/client/EventSendingUtil.java, modules/samples/sample-clients/kafka-producer/src/main/java/org/wso2/sp/sample/kafka/client/KafkaClient.java, pom.xml
=> Bug fix for http client

modules/samples/sample-clients/jms-consumer/pom.xml, modules/samples/sample-clients/jms-producer/pom.xml
> Fix JMS sample version issues.
=> Fix JMS sample version issues.

pom.xml
> Bump siddhi siddhi.io.jms & siddhi.io.http extensions versions.
=> Bump Siddhi Extension Versions.

modules/samples/sample-clients/mqtt-consumer/build.xml
> Optional properties added for user to give parameters.
=> Optional properties are added

modules/samples/sample-clients/wso2event-server/src/main/java/org/wso2/carbon/sample/server/DatabridgeTestServer.java
=> wso2event server modified

README.md, modules/distribution/pom.xml, pom.xml
> Bumped Dependencies Versions.
=>  Bump Dependencies Versions. 

modules/samples/artifacts/1001/ReceiveAndCount.siddhi
=> Giving meaning full names to the streams

modules/distribution/pom.xml, pom.xml
> Add tensorflow lib + bump dependency versions
=> Add tensorflow lib + bump dependency versions

modules/distribution/pom.xml, pom.xml
Adds `org.wso2.carbon.dashboards.samples.feature` feature to product distribution.
=> Add dashboard samples feature to product distribution

modules/samples/artifacts/PublishKafkaInBinaryFormat/PublishKafkaInBinaryFormat.siddhi, modules/samples/artifacts/PublishKafkaInJsonFormat/PublishKafkaInJsonFormat.siddhi
Add 'How to convert kafka libs to OSGI' in kafka samples' documentation.
=> Add 'How to convert kafka libs to OSGI' in kafka samples' documentation.

modules/samples/artifacts/WSO2EventProcessorSiddhiApp/WSO2EventProcessorSiddhiApp.siddhi
> Changes for samples
V#log replaced by @sink(type='log ')
=> Samples Modification

modules/samples/sample-clients/http-client/build.xml, modules/samples/sample-clients/http-client/src/main/java/org/wso2/sp/http/client/EventSendingUtil.java, modules/samples/sample-clients/http-client/src/main/java/org/wso2/sp/http/client/HttpClient.java, modules/samples/sample-clients/kafka-producer/build.xml, modules/samples/sample-clients/kafka-producer/src/main/java/org/wso2/sp/sample/kafka/client/EventSendingUtil.java, modules/samples/sample-clients/kafka-producer/src/main/java/org/wso2/sp/sample/kafka/client/KafkaClient.java, modules/samples/sample-clients/mqtt-client/build.xml, modules/samples/sample-clients/mqtt-client/src/main/java/org/wso2/sp/mqtt/client/EventSendingUtil.java, modules/samples/sample-clients/mqtt-client/src/main/java/org/wso2/sp/mqtt/client/MqttClient.java, modules/samples/sample-clients/rabbitmq-producer/build.xml, modules/samples/sample-clients/rabbitmq-producer/src/main/java/org/wso2/sp/sample/rabbitmq/producer/EventSendingUtil.java, modules/samples/sample-clients/rabbitmq-producer/src/main/java/org/wso2/sp/sample/rabbitmq/producer/RabbitMQProducer.java, modules/samples/sample-clients/tcp-client/build.xml, modules/samples/sample-clients/tcp-client/src/main/java/org/wso2/sp/tcp/client/EventSendingUtil.java, modules/samples/sample-clients/tcp-client/src/main/java/org/wso2/sp/tcp/client/TCPClient.java
=> Adding continuouslyReadFile option to samples clients

modules/distribution/carbon-home/LICENSE.txt, modules/distribution/src/assembly/bin.xml
> Add license file to the distribution
=> Add license file to the distribution

modules/samples/artifacts/PublishKafkaInJsonFormat/PublishKafkaInJsonFormat.siddhi, modules/samples/artifacts/ReceiveKafkaInTextFormatWithCustomMapping/ReceiveKafkaInTextFormatWithCustomMapping.siddhi
=> Changing description in Kafka Receiving sample

modules/samples/sample-clients/http-client/src/main/java/org/wso2/sp/http/client/EventSendingUtil.java, modules/samples/sample-clients/kafka-producer/src/main/java/org/wso2/sp/sample/kafka/client/EventSendingUtil.java, modules/samples/sample-clients/mqtt-client/src/main/java/org/wso2/sp/mqtt/client/EventSendingUtil.java, modules/samples/sample-clients/rabbitmq-producer/src/main/java/org/wso2/sp/sample/rabbitmq/producer/EventSendingUtil.java, modules/samples/sample-clients/tcp-client/src/main/java/org/wso2/sp/tcp/client/EventSendingUtil.java
> Add javadoc comments for public classes
=> Added javadoc comments

pom.xml
> carbon-analytics to 2.0.228
> siddhi to 4.0.1
> carbon-dashboards to 4.0.2
=> Bump carbon-analytics, siddhi, carbon-dashboard versions

modules/samples/artifacts/AggregateDataIncrementally/AggregateDataIncrementally.siddhi, modules/samples/artifacts/AggregateOverTime/AggregateOverTime.siddhi, modules/samples/artifacts/AlertsAndThresholds/AlertsAndThresholds.siddhi
=> Fixing description for AggregateOverTime and AlertAndThresholds sample

modules/samples/artifacts/AggregateDataIncrementally/AggregateDataIncrementally.siddhi
=> Fix steps on AggregateDataIncrementally sample

modules/samples/artifacts/HBaseSample/store-hbase.siddhi
HBase update works fine after a fix.
=> Uncommeting hbase-store update

modules/samples/artifacts/MongoSample/store-mongodb.siddhi
=> Improved MongoDBSample

pom.xml
> carbon-analytics to 2.0.234
> carbon-analytics-commons to 6.0.48
=> Bump analytics and analytics commons version

modules/samples/sample-clients/tcp-server/build.xml, modules/samples/sample-clients/tcp-server/src/main/java/org/wso2/sp/tcp/server/TCPServer.java
> Fix the issue configuration override in sample TCP server client where host, port properties should taken as system parameters in siddhi io tcp extension.
=> Fix configuration override issue in the TCP server sample client.

modules/samples/artifacts/AggregateDataIncrementally/AggregateDataIncrementally.siddhi, modules/samples/artifacts/HBaseSample/store-hbase.siddhi, modules/samples/artifacts/RDBMSSample/Store-rdbms.siddhi, modules/samples/artifacts/SolrSample/Store-solr.siddhi
Refactoring samples after testing...
=> Refactoring samples

pom.xml
=> bumping analytics and siddhi versions

modules/distribution/pom.xml, pom.xml
> Bumping dependency versions + dependency changes
=> Bumping dependency versions + dependency changes

modules/samples/artifacts/DataPreprocessing/DataPreprocessing.siddhi
> Removing MySQL setting up instruction since sample doesn't contain anything regarding databases
=> Changing description

modules/samples/artifacts/HBaseSample/store-hbase.siddhi, modules/samples/artifacts/MongoSample/store-mongodb.siddhi, modules/samples/artifacts/RDBMSSample/Store-rdbms.siddhi, modules/samples/artifacts/SolrSample/Store-solr.siddhi
> Some changes are made in store samples for user to understand the guide clearly.
=> Sample's Documentations

modules/distribution/carbon-home/conf/manager/deployment.yaml
=> Replace kakfa default port in manager runtime deployment.yaml

pom.xml
Bump analytics version to v2.0.247
=> Bump carbon-analytics version to v2.0.247

modules/samples/artifacts/RDBMSSample/Store-rdbms.siddhi
Made some edits. Please review these changes and apply them to the other samples as well.
=> Copy edits

pom.xml
=> Bump analytics version to v2.0.248

modules/distribution/carbon-home/LICENSE.txt, pom.xml
=> Bump RDBMS store version and update licence

modules/samples/artifacts/HelloKafka/HelloKafka.siddhi
=> Fix the Hello Kafka sample.

modules/samples/artifacts/PublishHTTPInJsonFormatWithCustomMapping/PublishHTTPInJsonFormatWithCustomMapping.siddhi
- Renaming SiddhiApp in the instruction to send Postman request
- Replacing `name`s with `id`s
=> Fixing minor issues in instructions

modules/samples/artifacts/StreamingRegressor/StreamingRegressor.siddhi
> Update Streaming Regressor sample
=> Update Streaming Regressor sample

pom.xml
> Updating release plugin to support autoVersionSubmodules
=> Updating release plugin

pom.xml
> upgrade the carbon-dashboards version to 4.0.9 for weekly release.
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
=> Bump the carbon-dashboards version to 4.0.9

modules/distribution/carbon-home/bin/dashboard.sh, modules/distribution/carbon-home/bin/editor.sh, modules/distribution/carbon-home/bin/manager.sh, modules/distribution/carbon-home/bin/worker.sh, modules/distribution/src/assembly/bin.xml
This PR fixes the issue in #441. The same issue existed in the other profiles as well, and hence this PR has fixes for all the profiles. 
Improve the usability of starting with a bash script. 
Fixing all bash scripts, and corresponding sh file modes in profiles. 
N/A
Fixing the responsiveness issue at stopping the bash scripts of SP profiles. 
N/A
N/A
N/A
N/A
N/A as this is the improvement in the bash script.
N/A
N/A
N/A
N/A 
Unix based environments. 
N/A
=> Fixing the issue #441

modules/samples/artifacts/ClusTreeSample/ClusTreeTestApp.siddhi, modules/samples/artifacts/ExtractNamedEntities/GplNLPFindNameEntityType.siddhi, modules/samples/artifacts/GeoDistanceCalculation/GeoDistanceCalculation.siddhi, modules/samples/artifacts/PMMLModelProcessorSample/PmmlModelProcessor.siddhi, modules/samples/artifacts/RScriptSample/RScriptSample.siddhi, modules/samples/artifacts/StreamingHoeffdingClassifierSample/hoeffding-adaptive-tree-sample.siddhi, modules/samples/artifacts/StreamingRegressor/StreamingRegressor.siddhi
=> Editing gpl sample descriptions

pom.xml
=> Update kernel version to 5.2.7

modules/distribution/pom.xml, pom.xml
> Adding Business Rules Template Editor
> https://github.com/wso2/carbon-analytics/pull/1110
=> Adding Business Rules Template Editor

modules/distribution/carbon-home/conf/manager/deployment.yaml, modules/distribution/carbon-home/conf/worker/deployment.yaml, modules/distribution/pom.xml, pom.xml
>Add permission provider for worker and manager runtime
>Add permission provider for worker and manager runtime
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> NA
=> Add permission provider for worker and manager runtime

modules/distribution/carbon-home/LICENSE.txt
=> Add updated license file

modules/distribution/pom.xml, modules/integration/pom.xml, modules/samples/sample-clients/http-client/pom.xml, modules/samples/sample-clients/http-server/pom.xml, modules/samples/sample-clients/jms-consumer/pom.xml, modules/samples/sample-clients/jms-producer/pom.xml, modules/samples/sample-clients/kafka-consumer/pom.xml, modules/samples/sample-clients/kafka-producer/pom.xml, modules/samples/sample-clients/mqtt-client/pom.xml, modules/samples/sample-clients/mqtt-consumer/pom.xml, modules/samples/sample-clients/pom.xml, modules/samples/sample-clients/rabbitmq-consumer/pom.xml, modules/samples/sample-clients/rabbitmq-producer/pom.xml, modules/samples/sample-clients/tcp-client/pom.xml, modules/samples/sample-clients/tcp-server/pom.xml, modules/samples/sample-clients/wso2event-client/pom.xml, modules/samples/sample-clients/wso2event-server/pom.xml, modules/tests/pom.xml, pom.xml
> Release version changed to 4.0.0-update1-SNAPSHOT so that next release is 4.0.0-update1 in accordance with weekly release builds
> In accordance with product releases every week
> Refactor release versions
=> Refactor release version

pom.xml
> Upgrade analytics version to 2.0.268
> Upgrade analytics version to 2.0.268 for SP update 1 release
> NA
>  NA
> NA
> NA
> NA
> NA
> NA
- Unit tests 
> Code coverage information
> Details about the test cases and coverage
> NA
> NA
> NA
=> Upgrade analytics version to 2.0.268

pom.xml
> Upgrade carbon-dashboards version
> Upgrade carbon-dashboards version
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
> NA
=> Upgrade carbon-dashboards version

modules/distribution/carbon-home/conf/dashboard/deployment.yaml, modules/distribution/carbon-home/conf/editor/deployment.yaml, modules/distribution/carbon-home/conf/manager/deployment.yaml, modules/distribution/carbon-home/conf/worker/deployment.yaml, modules/integration/tests-kubernetes-integration/src/test/resources/artifacts/docker-files/deployment-ha-node-1.yaml, modules/integration/tests-kubernetes-integration/src/test/resources/artifacts/docker-files/deployment-ha-node-2.yaml, modules/integration/tests-kubernetes-integration/src/test/resources/artifacts/docker-files/deployment-mysql.yaml, pom.xml
> Bump carbon-analytics version to 2.0.272 and refactor state.persistence files to reflect new changes
=> Refactor persistence property name. Bump carbon-analytics version

pom.xml
> Upgrade siddhi & analytics version for weekly release
> Upgrade siddhi & analytics version for weekly release
> Upgrade siddhi & analytics version for weekly release
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> java version "1.8.0_151"
> Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
> Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
> NA
=> Upgrade siddhi & analytics version for weekly release

modules/distribution/pom.xml, pom.xml
Adding csv extension into the SP.
Add the dependency in the pom.xml.
=> Changes in pom.xml

pom.xml
> Upgrade analytics version for weekly release
> Upgrade analytics version for weekly release
> Upgrade analytics version for weekly release
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> java version "1.8.0_151"
> Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
> Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
> NA
=> Upgrade analytics version for weekly release update3

pom.xml
> Upgrade analytics and dashboards version for weekly release
> Upgrade analytics and dashboards version for weekly release
> Upgrade analytics and dashboards version for weekly release
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> java version "1.8.0_151"
> Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
> Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
> NA
=> Upgrade analytics and dashboards version for weekly release

pom.xml
>Updating the version of Siddhi IO Kafka extension
=> Updating the version of Siddhi IO Kafka extension

modules/samples/artifacts/PublishWebSocketInXmlFormat/PublishWebSocketInXmlFormat.siddhi, modules/samples/artifacts/ReceiveWebSocketInXmlFormat/ReceiveWebSocketInXMLFormat.siddhi, modules/samples/sample-clients/pom.xml, modules/samples/sample-clients/websocket-producer/build.xml, modules/samples/sample-clients/websocket-producer/pom.xml, modules/samples/sample-clients/websocket-producer/src/main/java/org/wso2/sp/sample/websocket/server/EventSendingUtil.java, modules/samples/sample-clients/websocket-producer/src/main/java/org/wso2/sp/sample/websocket/server/WebSocketProducer.java, modules/samples/sample-clients/websocket-receiver/build.xml, modules/samples/sample-clients/websocket-receiver/pom.xml, modules/samples/sample-clients/websocket-receiver/src/main/java/org/wso2/sp/sample/websocket/receiver/WebSocketReceiver.java
> Adding samples and sample-client for siddhi-io-websocket
=> Adding samples for WebSocket

pom.xml
> Upgrade analytics version for weekly release
> Upgrade analytics version for weekly release
> Upgrade analytics version for weekly release
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> java version "1.8.0_151"
> Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
> Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
> NA
=> Upgrade carbon-analytics version to 2.0.285

modules/samples/artifacts/CassandraSample/Store-cassandra.siddhi, modules/samples/artifacts/SolrSample/Store-solr.siddhi
> Adding siddhi-store-cassandra sample.
> Removing the duplicate query error.
> Enable the user to work with Siddhi-Stores
=> Refactoring Solr sample and add Cassandra sample

pom.xml
Upgrade analytics, siddhi, dashboards version for update6
Upgrade analytics, siddhi, dashboards version for update6
Upgrade analytics, siddhi, dashboards version for update6
NA
NA
NA
NA
NA
NA
NA
NA
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
NA
=> Upgrade analytics, siddhi, dashboards version for update6

modules/distribution/pom.xml, pom.xml
To pack siddhi-execution-env to the product
=> packed siddhi-execution-env to the product

modules/distribution/pom.xml, modules/distribution/src/assembly/bin.xml, modules/distribution/src/scripts/forget-me.bat, modules/distribution/src/scripts/forget-me.sh, pom.xml
This PR adds the "forget-me" tool to the product.
=> Add forget-me tool

modules/distribution/src/assembly/bin.xml, modules/distribution/src/scripts/forgetme.bat, modules/distribution/src/scripts/forgetme.sh, pom.xml
> Embedding the new fixes for Forget_me tool for GDPR compliance
> Bump Forget_me tool version
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> Ubuntu 16.04, JDK 1.8_144
=> Bumped forget-me tool and carbon analytics version

modules/samples/artifacts/ReceiveEventsFromFile/ReceiveEventsFromFile.siddhi
Improved the instructions in the 'ReceiveEventsFromFile' sample.
=> Improved the instructions in the 'ReceiveEventsFromFile' sample

pom.xml
=> Bump carbon-dashboards version to v4.0.14

modules/samples/artifacts/RDBMSSample/Store-rdbms.siddhi, modules/samples/artifacts/ReceiveJMSInJsonFormat/ReceiveJMSInJsonFormat.siddhi, modules/samples/artifacts/ReceiveJMSInKeyvalueFormat/ReceiveJMSInKeyvalueFormat.siddhi
> Fixing instructions for SP samples (RDBMS store & JMS)
=> Fixing instructions for SP samples (RDBMS store & JMS)

modules/samples/artifacts/PublishEmailInTextFormat/PublishEmailInTextFormat.siddhi, modules/samples/artifacts/PublishEmailInXmlFormat/PublishEmailInXmlFormat.siddhi
=> Update the PublishEmailInXmlFormat.siddhi and PublishEmailInTextFormat.siddhi sample files

modules/distribution/src/policies/pages/cookie-policy.hbs, modules/distribution/src/policies/pages/index.hbs, modules/distribution/src/policies/pages/privacy-policy.hbs
=> Add cookie policy and privacy policy

modules/distribution/src/policies/pages/cookie-policy.hbs, modules/distribution/src/policies/pages/index.hbs, modules/distribution/src/policies/pages/privacy-policy.hbs
=> Fix typo in privacy policy page

pom.xml
upgraded to latest released versions
to have latest release versions
=> upgraded versions

pom.xml
=> upgraded carbon-analytics version

pom.xml
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Upgrading RDBMS siddhi extension version.

modules/samples/artifacts/PMMLModelProcessorSample/PmmlModelProcessor.siddhi
Provided the file path to the `SweetProductionRatePrediction.pmml` file in the instructions of the `PMMLModelProcessorSample.siddhi` app for easier access to the user.
=> Update the 'PMMLModelProcessorSample.siddhi' file's instructions

modules/samples/artifacts/PublishTcpInJsonFormat/PublishTcpInJsonFormat.siddhi, modules/samples/artifacts/ReceiveJMSInJsonFormat/ReceiveJMSInJsonFormat.siddhi, modules/samples/artifacts/ReceiveMQTTInXMLFormat/ReceiveMQTTInXMLFormat.siddhi, modules/samples/artifacts/ReceiveWSO2Events/ReceiveWSO2Events.siddhi
> Fixing instructions for the following samples:
> - PublishTcpInJsonFormat
> - ReceiveJMSInJsonFormat
> - ReceiveMQTTInXMLFormat
> - ReceiveWSO2Events
=> Fixing instructions for samples

modules/distribution/pom.xml, modules/samples/artifacts/TwitterPollingSample/TwitterPolling-sample.siddhi, modules/samples/artifacts/TwitterStreamingSample/TwitterStreaming-sample.siddhi, pom.xml
> Add siddhi-io-twitter extension and add samples
=> Add siddhi-io-twitter extension and add samples

modules/samples/artifacts/TwitterPollingSample/TwitterPolling-sample.siddhi, modules/samples/artifacts/TwitterStreamingSample/TwitterStreaming-sample.siddhi, pom.xml
> Update POM file and fix checkstyle issue
=> Update POM file and fix checkstyle issue

modules/distribution/pom.xml, modules/samples/artifacts/RedisSample/Store-redis.siddhi, pom.xml
> Packing Redis store extension with the product SP
=> Add Redis store extension and Sample

pom.xml
=> Bump json mapper version

modules/solutions/twitter-analytics/pom.xml, modules/solutions/twitter-analytics/siddhi-extensions/siddhi-execution-country/component/findbugs-exclude.xml, modules/solutions/twitter-analytics/siddhi-extensions/siddhi-execution-tokenizer/component/findbugs-exclude.xml
> Add findbug-exclude.xml file to the extensions
=> Add findbug-exclude.xml file to the extensions

modules/performance/README.md
>  Fix the [#480](https://github.com/wso2/product-sp/issues/480), where the instructions for using siddhi-execution-performance extension are missing.
> Updated README file to give the instructions to use the extension.
=> Update performance README.md file

modules/solutions/http-analytics/widgets/HTTPAnalyticsRequestStatistics/.babelrc, modules/solutions/http-analytics/widgets/HTTPAnalyticsRequestStatistics/package-lock.json, modules/solutions/http-analytics/widgets/HTTPAnalyticsRequestStatistics/package.json, modules/solutions/http-analytics/widgets/HTTPAnalyticsRequestStatistics/pom.xml, modules/solutions/http-analytics/widgets/HTTPAnalyticsRequestStatistics/src/HTTPAnalyticsRequestStatistics.jsx, modules/solutions/http-analytics/widgets/HTTPAnalyticsRequestStatistics/src/resources/dataProviderConf.json, modules/solutions/http-analytics/widgets/HTTPAnalyticsRequestStatistics/src/resources/widgetConf.json, modules/solutions/http-analytics/widgets/HTTPAnalyticsRequestStatistics/src/utils/WidgetChannelManager.js, modules/solutions/http-analytics/widgets/HTTPAnalyticsRequestStatistics/webpack.config.js
Create a line chart widget to show detailed table view of the request statistics in HTTP Dashboard (HTTP Analytics Solution)
Use react-vizGrammer to plot the table, querying data from database using SiddhiAppProvider
As a user,
I want to view the details of request statistics,
So that HTTP Server can be monitored.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
Chrome 64.0.3282.140
Firefox 60.0.1
N/A
=> Adding HTTPAnalyticsRequestStatistics Widget

modules/distribution/carbon-home/conf/dashboard/deployment.yaml, modules/distribution/carbon-home/conf/worker/deployment.yaml, modules/solutions/http-analytics/features/org.wso2.sp.solutions.http.analytics.feature/src/main/resources/p2.inf, modules/solutions/http-analytics/features/org.wso2.sp.solutions.http.analytics.feature/src/main/resources/templates/http-analytics-solution.json
A user should be able to deploy the siddhi app for HTTP solution easily
The user would be able to deploy the app through business-rule template manager easily
Created the template of the siddhi app and added to template manager
As a user,
I should be able to deploy HTTP Analytics Siddhi App easily,
for testing purposes.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
JDK 1.8.0_135
N/A
=> Adding Siddhi App for HTTP Solution as template

modules/solutions/twitter-analytics/features/org.wso2.sp.portal.twitter.analytics.solution.feature/src/main/resources/p2.inf
> Fix file path issue in the Twitter Analytics solution business rules template.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training …
=> Fix Twitter analytics business rule p2 file path issue

modules/distribution/pom.xml, modules/solutions/twitter-analytics/features/org.wso2.sp.portal.twitter.analytics.solution.feature/src/main/resources/template/twitter-analytics.json, modules/solutions/twitter-analytics/widgets/Emotions/src/Emotions.jsx, modules/solutions/twitter-analytics/widgets/TweetCounter/src/TweetCounter.jsx
> Fix Twitter Analytics Siddhi Extensions Jars copying and minor UI fixes.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content …
=> Fix Twitter analytics Siddhi Extension Jars Copying

modules/distribution/pom.xml, pom.xml
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Fix Twitter analytics Siddhi extensions dependency issue

modules/solutions/http-analytics/README.md
A README file for the HTTP Solution is added for ease of use
=>  Adding README file for HTTP Analytics Solution

modules/samples/artifacts/ActivityExplorer/ActivityExplorer.siddhi
> Add activity explorer siddhi app instructions
=> Add activity explorer siddhi app instructions

modules/solutions/http-analytics/features/org.wso2.sp.solutions.http.analytics.feature/pom.xml
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Update http analytics solution pom

modules/solutions/http-analytics/features/org.wso2.sp.solutions.http.analytics.feature/pom.xml
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Fix Http analytics solution feature build failure issue

modules/solutions/http-analytics/features/org.wso2.sp.solutions.http.analytics.feature/pom.xml
=> Fixing HTTP Analytics widgets not being copied issue

pom.xml
Upgrade dependency versions for SP alpha release
Upgrade dependency versions for SP alpha release
Upgrade dependency versions for SP alpha release
NA
NA
NA
NA
NA
NA
NA
NA
NA
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
NA
=> Upgrade dependency versions for SP alpha release

modules/solutions/twitter-analytics/widgets/EmotionsAnalysis/webpack.config.js, modules/solutions/twitter-analytics/widgets/TweetCountAnalysis/webpack.config.js
Fix generating map files in twitter analytics solution
Resolves #594 
Fix generating map files in twitter analytics solution
Fix generating map files in twitter analytics solution
NA
NA
NA
NA
NA
NA
NA
NA
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
NPM 5.4.2
NA
=> Fix generating map files in twitter analytics solution

modules/solutions/http-analytics/widgets/HTTPAnalyticsRequestCountFilter/src/HTTPAnalyticsRequestCountFilter.jsx, modules/solutions/http-analytics/widgets/HTTPAnalyticsResponseCodeFilter/src/HTTPAnalyticsResponseCodeFilter.jsx
Fix styles conflicting issue in http widgets
=> Fix styles conflicting issue in http widgets

modules/solutions/http-analytics/widgets/HTTPAnalyticsLatencyComparison/src/HTTPAnalyticsLatencyComparison.jsx, modules/solutions/http-analytics/widgets/HTTPAnalyticsLatencyOverTime/src/HTTPAnalyticsLatencyOverTime.jsx, modules/solutions/http-analytics/widgets/HTTPAnalyticsRequestCountComparison/src/HTTPAnalyticsRequestCountComparison.jsx, modules/solutions/http-analytics/widgets/HTTPAnalyticsRequestCountOverTime/src/HTTPAnalyticsRequestCountOverTime.jsx
=> Updated http-analytics widgets to handle No data scenario

modules/solutions/http-analytics/widgets/HTTPAnalyticsRequestCountFilter/src/HTTPAnalyticsRequestCountFilter.jsx
=> Fixing issue of filter widget not rendering properly at first

modules/solutions/activity-explorer/widgets/OpenTracingEvent/package.json, modules/solutions/activity-explorer/widgets/OpenTracingEvent/src/OpenTracingEvent.css, modules/solutions/activity-explorer/widgets/OpenTracingEvent/src/OpenTracingEvent.jsx, modules/solutions/activity-explorer/widgets/OpenTracingList/package.json, modules/solutions/activity-explorer/widgets/OpenTracingList/src/OpenTracingList.css, modules/solutions/activity-explorer/widgets/OpenTracingList/src/OpenTracingList.jsx
This PR fixes styles in following widgets in Activity Explorer dashboard.
- OpenTracingList
- OpenTracingEvent
=> Fix styles in Activity Explorer widgets

modules/solutions/activity-explorer/widgets/OpenTracingSearch/src/OpenTracingSearch.jsx, modules/solutions/activity-explorer/widgets/OpenTracingSearch/webpack.config.js
Improve open tracing widget styles
Improve open tracing widget styles
=> Improve open tracing widget styles

modules/distribution/pom.xml, pom.xml
Add siddhi-io-websocket extension into distribution
Add siddhi-io-websocket extension into distribution
=> Add siddhi-io-websocket extension into distribution

modules/solutions/activity-explorer/widgets/OpenTracingSearch/src/OpenTracingSearch.css, modules/solutions/activity-explorer/widgets/OpenTracingSearch/src/OpenTracingSearch.jsx
This PR fixe styles in **OpenTracingSearch** widget in Activity Explorer dashboard.
=> Fix OpenTracingSearch widget styles

modules/solutions/activity-explorer/widgets/OpenTracingEvent/package.json, modules/solutions/activity-explorer/widgets/OpenTracingList/package.json, modules/solutions/activity-explorer/widgets/OpenTracingSearch/package.json, modules/solutions/activity-explorer/widgets/OpenTracingVisTimeline/package.json, modules/solutions/http-analytics/widgets/HTTPAnalyticsLatencyComparison/package.json, modules/solutions/http-analytics/widgets/HTTPAnalyticsLatencyOverTime/package.json, modules/solutions/http-analytics/widgets/HTTPAnalyticsRequestCountComparison/package.json, modules/solutions/http-analytics/widgets/HTTPAnalyticsRequestCountFilter/package.json, modules/solutions/http-analytics/widgets/HTTPAnalyticsRequestCountOverTime/package.json, modules/solutions/http-analytics/widgets/HTTPAnalyticsRequestStatistics/package.json, modules/solutions/http-analytics/widgets/HTTPAnalyticsResponseCodeFilter/package.json, modules/solutions/twitter-analytics/widgets/Emotions/package.json, modules/solutions/twitter-analytics/widgets/EmotionsAnalysis/package.json, modules/solutions/twitter-analytics/widgets/Hashtag/package.json, modules/solutions/twitter-analytics/widgets/LiveTweets/package.json, modules/solutions/twitter-analytics/widgets/PopularTweets/package.json, modules/solutions/twitter-analytics/widgets/TopCountries/package.json, modules/solutions/twitter-analytics/widgets/TopSentiment/package.json, modules/solutions/twitter-analytics/widgets/TweetCountAnalysis/package.json, modules/solutions/twitter-analytics/widgets/TweetCounter/package.json, modules/solutions/twitter-analytics/widgets/WordCloud/package.json
This PR updates base widget version to 1.2.0.
=> Update base widget version to 1.2.0

pom.xml
Upgrade dependency versions for 4.2.0 beta release
Upgrade dependency versions for 4.2.0 beta release
=> Upgrade dependency versions for 4.2.0 beta release

pom.xml
Updating forgetme tool to the latest version
=>  Updating forgetme tool to the latest version

modules/solutions/activity-explorer/widgets/OpenTracingList/src/OpenTracingList.jsx, modules/solutions/activity-explorer/widgets/OpenTracingSearch/package.json, modules/solutions/activity-explorer/widgets/OpenTracingSearch/src/DateRangePicker/CustomTimeRangeSelector.jsx, modules/solutions/activity-explorer/widgets/OpenTracingSearch/src/DateRangePicker/DateRangePicker.jsx, modules/solutions/activity-explorer/widgets/OpenTracingSearch/src/DateRangePicker/DateTimePicker.jsx, modules/solutions/activity-explorer/widgets/OpenTracingSearch/src/DateRangePicker/GranularityModeSelector.jsx, modules/solutions/activity-explorer/widgets/OpenTracingSearch/src/OpenTracingSearch.css, modules/solutions/activity-explorer/widgets/OpenTracingSearch/src/OpenTracingSearch.jsx
This PR includes modifications in **Activity Explorer** dashboard in following widgets.
- Refator the UI.
- Integrate date time picker for date range fields.
- On selecting a row, browser redirects to the `timeline` page with selected `TRACEID`.
=> Refactor Activity Explorer dashboard widgets

modules/solutions/http-analytics/README.md, modules/solutions/http-analytics/features/org.wso2.sp.solutions.http.analytics.feature/src/main/resources/templates/http-analytics-solution.json
=> Minor update for the http-analytics template

modules/distribution/carbon-home/conf/dashboard/deployment.yaml
> Updating sample node config for Business Rules Manager, with HTTPS port
> https://github.com/wso2/carbon-analytics/pull/1310
=> Update sample node config for Business Rules Manager, with HTTPS port

modules/solutions/twitter-analytics/widgets/Hashtag/src/Hashtag.jsx, modules/solutions/twitter-analytics/widgets/LiveTweets/src/LiveTweets.jsx
This PR fixes following widgets in Twitter analytics dashboard.
- Fix UI of the information message displayed.
- Added **Refresh** button to show new tweets.
=> Fix Twitter analytics dashboard widget UIs

modules/solutions/message-tracer/widgets/OpenTracingSearch/src/DateRangePicker/CustomTimeRangeSelector.jsx, modules/solutions/message-tracer/widgets/OpenTracingSearch/src/DateRangePicker/DateRangePicker.jsx, modules/solutions/message-tracer/widgets/OpenTracingSearch/src/DateRangePicker/DateTimePicker.jsx, modules/solutions/message-tracer/widgets/OpenTracingSearch/src/OpenTracingSearch.css
This PR fixes an issue in year selection in **OpenTracingSearch** widget.
=> Fix year selection in OpenTracingSearch widget

modules/solutions/twitter-analytics/widgets/LiveTweets/package.json
Add `react-dom` dependency in LiveTweets widget.
=> Add react-dom dependency

modules/distribution/carbon-home/conf/manager/deployment.yaml, modules/distribution/carbon-home/conf/worker/deployment.yaml
> Change default configurations to https
=> [Distributed] Update deployment.yaml

modules/solutions/message-tracer/features/org.wso2.sp.portal.message.tracer.solution.feature/src/main/resources/business_rules/templates/message-tracing.json, modules/solutions/message-tracer/widgets/OpenTracingList/package.json, modules/solutions/message-tracer/widgets/OpenTracingList/src/OpenTracingList.jsx, modules/solutions/message-tracer/widgets/OpenTracingSearch/package.json, modules/solutions/message-tracer/widgets/OpenTracingVisTimeline/package.json, modules/solutions/message-tracer/widgets/OpenTracingVisTimeline/src/OpenTracingVisTimeline.css, modules/solutions/message-tracer/widgets/OpenTracingVisTimeline/src/OpenTracingVisTimeline.jsx
> Add css changes to the message tracer timeline and template
=> Add css changes to the message tracer timeline and template

modules/samples/artifacts/ReceiveWebSocketInXmlFormat/ReceiveWebSocketInXMLFormat.siddhi
=> Updated ReceiveWebSocketInXMLFormat sample comments

modules/samples/artifacts/SweetProductionDataPreprocessing/SweetProductionDataPreprocessing.siddhi
> Adding missing instructions of SweetProductionDataPreProcessing sample
> Improving sample
=> Add missing instructions of SweetProductionDataPreProcessing sample

modules/solutions/twitter-analytics/widgets/Emotions/src/Emotions.jsx, modules/solutions/twitter-analytics/widgets/TweetCounter/src/TweetCounter.jsx, modules/solutions/twitter-analytics/widgets/WordCloud/src/WordCloud.jsx, modules/solutions/twitter-analytics/widgets/WordCloud/src/resources/wordCloud.css
This PR fixes styles in following Twitter analytics dashboard widgets.
- Emotions
- TweetCounter
- WordCloud
=> Fix twitter analytics widget styles

modules/samples/artifacts/RScriptSample/RScriptSample.siddhi
=>  Updating prerequisites in RScriptSample

modules/samples/artifacts/TensorflowSample/TensorFlowTestApp.siddhi
=> Improve TensorFlowSample

modules/samples/artifacts/MarkovChainSample/MarkovChainSample.siddhi, modules/samples/artifacts/MarkovChainSample/MarkovChainSimulator.json, modules/samples/artifacts/PublishHTTPInJsonFormatWithCustomMapping/PublishHTTPInJsonFormatWithCustomMapping.siddhi, modules/samples/artifacts/PublishHttpInXmlFormatWithCustomMapping/PublishHttpInXmlFormatWithCustomMapping.siddhi, modules/samples/artifacts/SentimentSample/sentimentExtensionSample.siddhi
=> Fix issues in editor samples

modules/samples/artifacts/ClusTreeSample/ClusTreeTestApp.siddhi, modules/samples/artifacts/ExtreamBottomK/ExtremaBottomK.siddhi, pom.xml
Fix issues editor samples
Upgrade dependency versions
=> Fix issues editor samples

modules/distribution/src/policies/pages/cookie-policy.hbs, modules/distribution/src/policies/pages/index.hbs, modules/distribution/src/policies/pages/privacy-policy.hbs, modules/distribution/src/policies/public/css/styles.css
Fix styles for policies page and moved styles to css
Improve Ux
=> Fix styles for policies page

modules/samples/artifacts/ExtreamBottomK/ExtremaBottomK.siddhi
> Fixing ExtremaBottomK Sample
> Fixing sample
=> Fix ExtremaBottomK Sample

modules/samples/artifacts/MessageTracer/message-tracer.siddhi
=> Add siddhi app description in message tracer sample

pom.xml
Fix issue in carbon-dashboards version
=> Fix issue in carbon-dashboards version

modules/distribution/carbon-home/LICENSE.txt
=> Upgrade license.txt

modules/solutions/message-tracer/widgets/OpenTracingVisTimeline/src/OpenTracingVisTimeline.jsx
> calculate the step value for x-axis
=> Fix timeline range according to data's time span

modules/solutions/http-analytics/features/org.wso2.sp.solutions.http.analytics.feature/src/main/resources/templates/http-analytics-solution.json
$subject (Fixes https://github.com/wso2/product-sp/issues/688) 
N/A as no functionality is changed
=> Improve field description in http-analytics business rules

pom.xml
Fix the build failure issue
Fix the build failure issue
Remove the suitXML configuration in the parent pom file
=> Fix the build failure issue

modules/solutions/message-tracer/components/open-tracer-client/org.wso2.sp.open.tracer.client/pom.xml
Fix build failure issue
Fix build failure issue
=> Fix build failure issue

pom.xml
Upgrade dependencies for 4.3.0M1
Upgrade dependencies for 4.3.0M1
Upgrade dependencies for 4.3.0M1
=> Upgrade dependencies for 4.3.0M1

modules/solutions/message-tracer/components/open-tracer-client/org.wso2.sp.open.tracer.client/src/main/java/org/wso2/sp/open/tracer/client/AnalyticsTracerConfig.java, modules/solutions/message-tracer/components/open-tracer-client/org.wso2.sp.open.tracer.client/src/main/java/org/wso2/sp/open/tracer/client/AnalyticsTracerLoader.java, modules/solutions/message-tracer/components/open-tracer-client/org.wso2.sp.open.tracer.client/src/main/java/org/wso2/sp/open/tracer/client/Constants.java, modules/solutions/message-tracer/components/open-tracer-client/org.wso2.sp.open.tracer.client/src/main/java/org/wso2/sp/open/tracer/client/StreamProcessorTracerClient.java
=> Make tracer's service name configurable from service side

modules/solutions/http-analytics/README.md, modules/solutions/twitter-analytics/README.md
=> Fix portal URL in http analytics and twitter solution README

modules/distribution/pom.xml, pom.xml
Add siddhi-execution-json extension to the distribution
Add siddhi-execution-json extension to the distribution
Add siddhi-execution-json extension to the distribution
NA
NA
NA
NA
NA
Available in the extension level
Available in the extension level
NA
NA
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
NA
=> Add siddhi-execution-json extension to the distribution

pom.xml
=> Bump version for M3 release

modules/distribution/pom.xml, pom.xml
```diff
-DO NOT MERGE, until analytics-solutions 1.0.0 is released
```
$subject
N/A
=> Rename of solutions dependency after move to analytics-solutions repo

modules/performance/README.md, modules/performance/extension/siddhi-execution-performance/component/src/main/java/org/wso2/extension/siddhi/execution/throughput/CalculatePerformanceStreamProcessorExtension.java
Include a flush method in file stream to get the data being wrote to the out put text file and change the output directory name as 'performance-metrics'.
Refer to issue #741
=> Change Output file directory and include flush method

pom.xml
Bump analytics dependency versions.
=> Bump analytics dependency versions.

modules/distribution/carbon-home/conf/worker/deployment.yaml
> IS-Analytics uses geo-location database for analytics part. Hence we need geo location data source in the product SP to work.
=> Adding datasource for geo-location data

modules/distribution/carbon-home/conf/dashboard/deployment.yaml, modules/distribution/carbon-home/conf/worker/deployment.yaml, modules/distribution/pom.xml, pom.xml
=> Add ei.analytics.feature

modules/distribution/carbon-home/conf/dashboard/deployment.yaml, modules/distribution/carbon-home/conf/worker/deployment.yaml
Instead of creating STATS_Db outside the distribution, this will create the db inside the worker/database directory,
=> Moving stats DB inside the distribution

modules/distribution/pom.xml, pom.xml
This PR is to modify the ei.analytics.widget artifact ids and esbanalytics extension dependency entries.
=> Modify EI Analytics widgets and extension

modules/distribution/pom.xml, pom.xml
=>  Bump dependency versions

pom.xml
Bump analytics solutions version.
=> Bump analytics solutions version.

pom.xml
Bump dependency versions for the release.
=>  Bump dependency versions for the Beta release.

modules/distribution/carbon-home/conf/dashboard/deployment.yaml, modules/distribution/carbon-home/conf/worker/deployment.yaml, modules/distribution/pom.xml, pom.xml
This PR will remove APIM analytics features getting pack in product distribution.
=> Remove APIM analytics feature

modules/distribution/carbon-home/conf/dashboard/deployment.yaml, modules/distribution/carbon-home/conf/worker/deployment.yaml, modules/distribution/pom.xml, pom.xml
=> Revert "Remove APIM analytics feature"

modules/distribution/pom.xml, modules/integration/pom.xml, modules/integration/test-results-service/pom.xml, modules/integration/tests-kubernetes-integration/pom.xml, modules/performance/extension/siddhi-execution-performance/component/pom.xml, modules/performance/extension/siddhi-execution-performance/pom.xml, modules/performance/pom.xml, modules/performance/sample-clients/pom.xml, modules/performance/sample-clients/tcp-client/pom.xml, modules/samples/sample-clients/http-client/pom.xml, modules/samples/sample-clients/http-server/pom.xml, modules/samples/sample-clients/is-analytics-client/pom.xml, modules/samples/sample-clients/jms-consumer/pom.xml, modules/samples/sample-clients/jms-producer/pom.xml, modules/samples/sample-clients/kafka-consumer/pom.xml, modules/samples/sample-clients/kafka-producer/pom.xml, modules/samples/sample-clients/mqtt-client/pom.xml, modules/samples/sample-clients/mqtt-consumer/pom.xml, modules/samples/sample-clients/pom.xml, modules/samples/sample-clients/rabbitmq-consumer/pom.xml, modules/samples/sample-clients/rabbitmq-producer/pom.xml, modules/samples/sample-clients/tcp-client/pom.xml, modules/samples/sample-clients/tcp-server/pom.xml, modules/samples/sample-clients/websocket-producer/pom.xml, modules/samples/sample-clients/websocket-receiver/pom.xml, modules/samples/sample-clients/wso2event-client/pom.xml, modules/samples/sample-clients/wso2event-server/pom.xml, modules/tests/pom.xml, pom.xml
Set development version to 4.3.0-rc2-SNAPSHOT to comply the scheduled weekly releases process.
=> Set development version to 4.3.0-rc2-SNAPSHOT.

modules/distribution/carbon-home/conf/dashboard/deployment.yaml, modules/distribution/carbon-home/conf/editor/deployment.yaml, modules/distribution/carbon-home/conf/manager/deployment.yaml, modules/distribution/carbon-home/conf/worker/deployment.yaml, modules/distribution/pom.xml, pom.xml
> The purpose of this PR is to add transport configuration for siddhi store API and reduce the size of the RDBMS data source connection pool size. 
> Fixes added for Siddhi Store API and RDBMS connection pool size
> Update the pom files with dependency versions and update the configuration. Remove the stream processor core dependency for editor runtime.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
=> Several fixes for Siddhi Store API and RDBMS connection pool size

modules/samples/artifacts/TensorflowSample/TensorFlowTestApp.siddhi
> The curl command and the Postman request provided in the steps cause an error. This fixes the error.
=> Fix in curl command and postman request in TensorflowTestApp sample.

modules/distribution/carbon-home/conf/worker/deployment.yaml
=> Add HA configurations to worker

modules/distribution/carbon-home/conf/dashboard/deployment.yaml
=> Fix the status dashboard query issue

modules/samples/artifacts/PublishEmailInTextFormat/PublishEmailInTextFormat.siddhi
> The instruction in the sample "PublishEmailInTextFormat" needs to be edited
>In the instruction as it is stated under viewing the result is different from the actual email(output) received.
> Existing Instruction
> Updated Instruction
=> Sample(PublishEmailInTextFormat) instruction correction

modules/samples/artifacts/SentimentSample/README.txt, modules/samples/artifacts/SentimentSample/sentimentExtensionSample.siddhi, modules/samples/artifacts/StreamingHoeffdingClassifierSample/hoeffding-adaptive-tree-sample.siddhi
The instructions of the StreamingHoeffdingClassifier sample and Sentiment sample should be corrected.
The port number of the curl commands given in the Sentiment sample should be corrected.
The stream-name of curl commands and the postman request given in the StreamingHoeffdingClassifier sample should be corrected.
=> Sample (StreamingHoeffdingClassifier) and Sample (Sentiment) Instruction Correction

pom.xml
=> Bump the extensions version

modules/samples/artifacts/RScriptSample/RScriptSample.siddhi
Add new parameters time and temp into the dataOut stream in RScript sample.
To correct the dataOut stream definition in RScript sample.
=> Add new parameters into dataOut stream in RScript sample

modules/distribution/pom.xml
adding valid value for artifactId element in modules/distribution/pom.xml as it should be as in a generic way as other products.
=> Added correct artfactid

modules/performance/extension/siddhi-execution-performance/component/pom.xml, modules/performance/extension/siddhi-execution-performance/component/src/main/java/org/wso2/extension/siddhi/execution/throughput/CalculatePerformanceStreamProcessorExtension.java, modules/performance/extension/siddhi-execution-performance/pom.xml
=> Fix pom files and checkstyle issues in performance directory

modules/distribution/carbon-home/conf/manager/deployment.yaml
=> Update SP_MGT_DB description in deployment configs

modules/distribution/carbon-home/bin/editor.bat, modules/distribution/carbon-home/bin/editor.sh
added ability to run from path with spaces
added quotes to starting scripts
=> fixed starting with spaces in path

pom.xml
=> Add siddhi-io-cdc version

modules/distribution/carbon-home/conf/worker/deployment.yaml
$subject. Fixes https://github.com/wso2/product-sp/issues/887
$subject
=> Fix EI_Analytics_DB pointing to diff folder

modules/performance/README.md, modules/performance/extension/siddhi-execution-performance/component/src/main/java/org/wso2/extension/siddhi/execution/throughput/CalculatePerformanceStreamProcessorExtension.java
=> Improve perf readme and fix headers

modules/samples/artifacts/PublishKafkaInAvroFormat/PublishKafkaInAvroFormatUsingSchemaRegistry.siddhi, modules/samples/artifacts/PublishKafkaInAvroFormat/PublishKafkaInCustomAvroFormat.siddhi, modules/samples/sample-clients/kafka-avro-consumer/build.xml, modules/samples/sample-clients/kafka-avro-consumer/pom.xml, modules/samples/sample-clients/kafka-avro-consumer/src/main/java/org/wso2/sp/sample/kafka/avro/consumer/KafkaReceiver.java, modules/samples/sample-clients/pom.xml, pom.xml
> $subject
> Added two samples for avro mapper using custom mapping and using  schema registry with kafka
=> Add avro mapper samples

modules/samples/sample-clients/apim-event-client/pom.xml, modules/samples/sample-clients/pom.xml
=> Add apim event client to the build

modules/distribution/pom.xml, pom.xml
- Bump dependency versions
- Add siddhi-io-nats extension.
=> Bump dependency versions and add siddhi-io-nats extension.

modules/distribution/carbon-home/conf/dashboard/deployment.yaml, modules/distribution/pom.xml, pom.xml
> Add Data Search Dashboard and its default configuration
=> Add Data Search Dashboard

modules/samples/artifacts/PublishSNMPEventWithCustomKeyvalue/SNMPSetRequestApp.siddhi, modules/samples/artifacts/ReceiveSNMPEventWithCustomKeyvalue/SNMPGetRequestApp.siddhi
The samples with instructions of how to publish and receive events using siddhi-io-snmp 
To easy to understand how snmp works with siddhi.
Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
=> add samples for snmp

modules/samples/artifacts/InfluxDBSample/store-influxdb.siddhi
> Add sample for connector siddhi-store-influxdb
>  To make it easy to use the connector and understand how it works.
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes 
> sample for performing insert, insert or update, delete, read and contains operations for influxdb store.
=> sample for siddhi-store-influxdb

modules/distribution/carbon-home/conf/worker/deployment.yaml
Reduce the frequency of heart beat update interval and add new configurable values
=> Add worker deployment.yaml changes

modules/distribution/pom.xml, modules/distribution/src/assembly/filter.properties, modules/integration/pom.xml, modules/performance/pom.xml, modules/samples/sample-clients/apim-event-client/pom.xml, modules/samples/sample-clients/ei-analytics-client/pom.xml, modules/samples/sample-clients/http-client/pom.xml, modules/samples/sample-clients/http-server/pom.xml, modules/samples/sample-clients/is-analytics-client/pom.xml, modules/samples/sample-clients/jms-consumer/pom.xml, modules/samples/sample-clients/jms-producer/pom.xml, modules/samples/sample-clients/kafka-avro-consumer/pom.xml, modules/samples/sample-clients/kafka-consumer/pom.xml, modules/samples/sample-clients/kafka-producer/pom.xml, modules/samples/sample-clients/mqtt-client/pom.xml, modules/samples/sample-clients/mqtt-consumer/pom.xml, modules/samples/sample-clients/pom.xml, modules/samples/sample-clients/prometheus-client/pom.xml, modules/samples/sample-clients/rabbitmq-consumer/pom.xml, modules/samples/sample-clients/rabbitmq-producer/pom.xml, modules/samples/sample-clients/tcp-client/pom.xml, modules/samples/sample-clients/tcp-server/pom.xml, modules/samples/sample-clients/websocket-producer/pom.xml, modules/samples/sample-clients/websocket-receiver/pom.xml, modules/samples/sample-clients/wso2event-client/pom.xml, modules/samples/sample-clients/wso2event-server/pom.xml, modules/tests/pom.xml, pom.xml
=> Update versions for alpha release

modules/distribution/pom.xml, pom.xml
=> Change metrics dependency

modules/distribution/pom.xml, modules/integration/pom.xml, modules/performance/pom.xml, modules/samples/artifacts/PublishEventsToFile/PublishEventsToFile.siddhi, modules/samples/sample-clients/apim-event-client/pom.xml, modules/samples/sample-clients/ei-analytics-client/pom.xml, modules/samples/sample-clients/http-client/pom.xml, modules/samples/sample-clients/http-server/pom.xml, modules/samples/sample-clients/is-analytics-client/pom.xml, modules/samples/sample-clients/jms-consumer/pom.xml, modules/samples/sample-clients/jms-producer/pom.xml, modules/samples/sample-clients/kafka-avro-consumer/pom.xml, modules/samples/sample-clients/kafka-consumer/pom.xml, modules/samples/sample-clients/kafka-producer/pom.xml, modules/samples/sample-clients/mqtt-client/pom.xml, modules/samples/sample-clients/mqtt-consumer/pom.xml, modules/samples/sample-clients/pom.xml, modules/samples/sample-clients/prometheus-client/pom.xml, modules/samples/sample-clients/rabbitmq-consumer/pom.xml, modules/samples/sample-clients/rabbitmq-producer/pom.xml, modules/samples/sample-clients/tcp-client/pom.xml, modules/samples/sample-clients/tcp-server/pom.xml, modules/samples/sample-clients/websocket-producer/pom.xml, modules/samples/sample-clients/websocket-receiver/pom.xml, modules/samples/sample-clients/wso2event-client/pom.xml, modules/samples/sample-clients/wso2event-server/pom.xml, modules/tests/pom.xml, pom.xml
This PR contains,
- Dependency updates
- Fixes for samples
=> Prepare for 4.4.0-beta2 release

modules/distribution/carbon-home/LICENSE.txt, pom.xml
=> Update dependency versions and license file

modules/distribution/pom.xml, pom.xml
Add Coordination Listener feature to product-sp. This feature has being added to worker, manager and editor profiles.
In a clustered deployment, this feature allows to do leader-aware event processing. 
TODO
Coordination Listener feature - In a clustered deployment, this feature allows to do leader-aware event processing. 
TODO
> TODO
> https://github.com/wso2/carbon-analytics/pull/1609
> N/A
> Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
> HA cluster with MySQL cluster DB.
> MySQL Server version: 5.7.21 MySQL …
=> Add Coordination Listener feature to product-sp

pom.xml
=> Bump dependency version with latest releases

pom.xml
=> Bump carbon config & secure vault dependencies

modules/samples/artifacts/RDBMSSample/Store-rdbms.siddhi
$Subject. This will allow RDBMS sample to run without adding certs
=> Add useSSL property to JDBC URL

modules/samples/artifacts/PublishRabbitmqInXmlFormat/PublishRabbitmqInXmlFormat.siddhi
=> Update siddhi app to work with default rabbitMQ installation

modules/samples/sample-clients/wso2event-server/src/main/java/org/wso2/carbon/sample/server/DatabridgeTestServer.java
=> Fix binary server startup issue

modules/samples/sample-clients/tcp-client/src/main/java/org/wso2/sp/tcp/client/TCPClient.java
=> Fix TCP client to be compatible with new text mapping implementation

modules/distribution/carbon-home/conf/dashboard/deployment.yaml, modules/distribution/carbon-home/conf/worker/deployment.yaml
$subject
Fixes https://github.com/wso2/product-sp/issues/983
N/A
=> Disable close on exit tag for Metrics DB

modules/samples/artifacts/PublishHttpInJsonFormat/PublishHttpInJsonFormat.siddhi, modules/samples/artifacts/PublishKafkaInBinaryFormat/PublishKafkaInBinaryFormat.siddhi, modules/samples/artifacts/PublishKafkaInJsonFormat/PublishKafkaInJsonFormat.siddhi, modules/samples/artifacts/ReceiveMQTTInXMLFormat/ReceiveMQTTInXMLFormat.siddhi, modules/samples/artifacts/TextMappingWithInmemoryTransport/TextMappingWithInmemoryTransport.siddhi, modules/samples/sample-clients/http-server/src/main/java/org/wso2/sp/http/server/HttpServerListener.java, modules/samples/sample-clients/http-server/src/main/java/org/wso2/sp/http/server/HttpServerListenerHandler.java, modules/samples/sample-clients/http-server/src/main/java/org/wso2/sp/http/server/HttpServerMain.java
> Fix issue https://github.com/wso2/product-sp/issues/980
=> Fix issues in samples

modules/samples/artifacts/HttpRequestResponseSample/HttpRequestResponseSample.siddhi, modules/samples/sample-clients/http-server/src/main/java/org/wso2/sp/http/server/HttpServerListener.java
=> Add a sample for http request-response scenario

modules/samples/artifacts/PublishHl7InEr7Format/PublishHl7InER7Format.siddhi
Fix issue in Hl7 Sample
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Fix issue in Hl7 Sample

pom.xml
=> Update component dependencies

modules/distribution/pom.xml, modules/samples/artifacts/PublishKafkaInAvroFormat/PublishKafkaInAvroFormatUsingSchemaRegistry.siddhi, pom.xml
=> Add avro jar to distribution and fix sample documentation

modules/distribution/carbon-home/conf/worker/deployment.yaml
Fix the active passive change due to database slowness
=> Add worker deployment.yaml change for HA

modules/distribution/carbon-home/LICENSE.txt, pom.xml
=> Update license file

modules/distribution/src/policies/pages/index.hbs
=> Add license

modules/distribution/pom.xml, modules/distribution/src/assembly/bin.xml
> Download and add the latest in-place tool to the product distribution
=> Download and add the latest in-place tool
