wso2/product-sp

modules/samples/artifacts/0004/RoundRobinPlan.siddhi

changing sample  for Publishing Events to Multiple Destinations Using the Round Robin Strategy as the  sink requires multiple destinations to be mentioned inside distribution annotation.

Changing multiple destination configuration

---

modules/samples/sample-clients/wso2event-client/build.xml
modules/samples/sample-clients/wso2event-server/build.xml
pom.xml

Upgrading the dependencies to Kernel 5.2.0
Having the latest kernel dependencies in product-sp
https://github.com/wso2/carbon-analytics-common/pull/389
https://github.com/wso2/carbon-metrics/pull/65
https://github.com/wso2/carbon-analytics/pull/540

Kernel 5.2.0 migration

---

modules/distribution/pom.xml
pom.xml

Integrate SP with an Identity Provider
User authentication can be done through Identity Provider
Adding idp.client, auth.rest.api and msf4j.interceptor.common features from carbon-analytics-common while removing the msf4j.interceptor.common feature from carbon-analytics
https://github.com/wso2/carbon-analytics-common/pull/392

Adding authentication features

---

pom.xml

Bump carbon dashboards version from 4.0.0.m10 to 4.0.0.m15
4.0.0.m15 contains bug fixes for several issues reported on carbon dashboards

bumping carbon dashboards version

---

modules/distribution/pom.xml
pom.xml

This PR adds `org.wso2.carbon.dashboards.samples.feature` samples feature and bumps `carbon-dashboards` version to v4.0.0.m17.
Add dashboard samples feature & bump dashboard version to 4.0.0.m17

Add dashboard samples feature & bump dashboard version to 4.0.0.m17

---

modules/distribution/carbon-home/conf/manager/deployment.yaml
modules/distribution/src/assembly/bin.xml

> Currently transport configuration directories of other runtimes will get copied to the manager runtime's transport conf directory.  Therefore, removing those unnecessary directories in wso2/manager/conf/transports

Removing unnecessary directories in wso2/manager/conf/transports

---

pom.xml

Current carbon-dashboards version is `4.0.0-alpha`
Bump carbon-dashboards version to `4.0.0.alpha2`

Bump carbon-dashboards version to 4.0.0.alpha2

---

pom.xml

This PR bumps the carbon-dashboards version to 4.0.0.alpha3.

Bump carbon-dashboards version to 4.0.0.alpha3

---

modules/samples/sample-clients/http-client/src/main/java/org/wso2/sp/http/client/HttpClient.java
modules/samples/sample-clients/kafka-consumer/src/main/java/org/wso2/sp/sample/kafka/consumer/KafkaReceiver.java
modules/samples/sample-clients/kafka-producer/src/main/java/org/wso2/sp/sample/kafka/client/KafkaClient.java
modules/samples/sample-clients/tcp-client/src/main/java/org/wso2/sp/tcp/client/StoreTestClient.java
modules/samples/sample-clients/tcp-client/src/main/java/org/wso2/sp/tcp/client/TCPClient.java
modules/samples/sample-clients/tcp-server/src/main/java/org/wso2/sp/tcp/server/TCPServer.java
modules/samples/sample-clients/wso2event-client/src/main/java/org/wso2/carbon/sample/wso2event/Client.java
modules/samples/sample-clients/wso2event-client/src/main/java/org/wso2/carbon/sample/wso2event/DataPublisherUtil.java
modules/samples/sample-clients/wso2event-server/src/main/java/org/wso2/carbon/sample/server/DatabridgeTestServer.java
modules/samples/sample-clients/wso2event-server/src/main/java/org/wso2/carbon/sample/server/WSO2EventServerUtil.java

This pr contain a fix for checkstyle detected bugs when building in windows. There is a bug in checkstyles that some checkstyle violations are not detected in linux, but detected when building the project in windows.
Removes checkstyle detected bugs.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
- Unit tests 
N/A
N/A
N/A
N/A
N/A
N/A
N/A

Adding fixes for checkstyle violations detected when building in windows

---

modules/distribution/carbon-home/conf/dashboard/deployment.yaml
modules/distribution/pom.xml
pom.xml

This PR bumps the carbon-dashboards version to 4.0.0.alpha4 and add dependencies for common permission provider module.

Bump carbon-dashboards version

---

modules/distribution/carbon-home/bin/carbon.bat
modules/distribution/carbon-home/bin/dashboard/carbon.bat
modules/distribution/carbon-home/bin/editor/carbon.bat
modules/distribution/carbon-home/bin/manager/carbon.bat
modules/distribution/carbon-home/bin/worker/carbon.bat

Fixes #219 
Prevent global setting of environment variables
Enables the path and runtime environment variables to be set locally, so that the implicit `endlocal` call will clear them upon exit.

Add fix for path issue in Windows, fixes #219

---

modules/samples/sample-clients/pom.xml
modules/samples/sample-clients/rabbitmq-consumer/build.xml
modules/samples/sample-clients/rabbitmq-consumer/pom.xml
modules/samples/sample-clients/rabbitmq-consumer/src/main/java/org/wso2/sp/sample/rabbitmq/consumer/RabbitMQReceiver.java

> To demonstrates how to configure WSO2 Stream Processor to send events via RabbitMQ transport in xml format using mapping,and view the output on the rabbitmq-consumer. But the rabbitmq-consumer is not available in sample-clients of product-sp.
And also user can override non-optional properties( uri, exchange.name and type of mapping).
> Existing clients in product-sp

RabbitMQ sample consumer 

---

pom.xml

- Bumps Carbon UI Server from 0.12.4 to **0.14.1**

Bump Carbon UI Server to v0.14.1

---

modules/distribution/pom.xml
pom.xml

> Pack the owsap dependency with distribution
> Pack the owsap feature in all runtimes
> Use feature.group to conform with standard when packing features in runtimes
> Bump Siddhi to beta15
> Bump carbon analytics common to 6.0.29
> Bump carbon analytics to 2.0.195

Used owsap feature in distribution + version upgrades

---

modules/distribution/carbon-home/conf/dashboard/deployment.yaml
modules/distribution/pom.xml
pom.xml

Bumps,
- Carbon UI Server version to 0.17.0
- Carbon Dashboards version to 4.0.0.beta3
- MSF4J version to 2.5.0-beta
- Carbon Analytics Common version to 6.0.36
- Carbon Analytics version to 2.0.197
- Siddhi version to 4.0.0-beta18
Removes,
- Carbon Transport v5.0.0 related dependencies
- Carbon Messaging v3.0.01 releated dependencies

Bump Carbon Dashboards version to v4.0.0.beta3

---

pom.xml

- Carbon Deployment version to v5.1.9
- Fixes #333 

Bump Carbon Deployment version to v5.1.9

---

pom.xml

- Bumps MSF4J version to v2.5.1
- Fixes #331 

Bump MSF4J version to v2.5.1

---

pom.xml

- bump msf4j to v2.5.2
- bump carbon-analytics-common version to v6.0.51
- bump carbon-dashboards version to v4.0.7

Bump msf4j, carbon-analytics-common, carbon-dashboard versions

---

modules/samples/artifacts/ReceiveHTTPInJsonFormatWithCustomMapping/ReceiveHTTPInJsonFormatWithCustomMapping.siddhi

- Changed content type of Postman request to `application/json`
- Removed comma which causes `bad string` error in Postman request
- Changed the name in viewing the results

Fixing instructions

---

modules/distribution/carbon-home/LICENSE.txt
pom.xml

Bump carbon dashboards version to 4.0.8 and update license file for dashboard jars

Bumping Carbon Dashboards version to 4.0.8

---

modules/samples/artifacts/ReceiveWSO2Events/ReceiveWSO2Events.siddhi

> added ant command's argument since editor mode's thrift server starts in a different port

Fix for Receive wso2 event sample description

---

modules/distribution/carbon-home/conf/manager/deployment.yaml
pom.xml

Upgrade analytics and coordination version for weekly release 
Add missing data source conf for manager runtime
Upgrade analytics and coordination version for weekly release 
Add missing data source conf for manager runtime
Upgrade analytics and coordination version for weekly release 
Add missing data source conf for manager runtime
NA
NA
NA
NA
NA
NA
NA
NA
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
NA

Add missing datasource conf in manager runtime and Upgrade carbon-coordination and analytics version

---

modules/distribution/carbon-home/conf/worker/deployment.yaml

After enabling matrices in worker instance, manually needed to change jdbc reporting and scheduled clean up state to true.

Made JDBC reporting and scheduled cleanup state to true by default. #515

---

modules/distribution/pom.xml
pom.xml

Adding SQS IO extension to the product.
This extension allows a user to define a source/sink to consume/publish messages from/to a AWS SQS Queue.
https://docs.google.com/document/d/168kc6rESZvsUWecoW01AomdS6B-JE0d9ks4ADei2-L0/edit?usp=sharing
JDK v1.8.0_161

Add SQS Source extension

---

modules/distribution/carbon-home/conf/editor/deployment.yaml

Changing http listen address to 0.0.0.0 instead of localhost for remote access. Since [#1158](https://github.com/wso2/carbon-analytics/issues/1158) [#1207](https://github.com/wso2/carbon-analytics/issues/1207) issues are fixed we can allow remote access to Editor.

Change http listen address to 0.0.0.0 instead of localhost for remote access

---

modules/distribution/carbon-home/conf/manager/deployment.yaml
pom.xml

Update manager runtime with new configs for zookeeper configuration
Bump carbon-coordination to 2.0.16

Update manager runtime configs. Bump carbon-coordination versions

---

modules/distribution/pom.xml
modules/solutions/http-analytics/features/etc/feature.properties
modules/solutions/http-analytics/features/org.wso2.sp.solutions.http.analytics.feature/pom.xml
modules/solutions/http-analytics/features/org.wso2.sp.solutions.http.analytics.feature/src/main/resources/p2.inf
modules/solutions/http-analytics/pom.xml
modules/solutions/http-analytics/widgets/pom.xml
modules/solutions/pom.xml
pom.xml

Copy the compiled widgets when the SP pack is build
During SP back build, this will copy needed HTTP Analytics widgets to the /portal/extension/widget folder
Using feature installation to copy resources
As a system,
I want to copy the widget resource at every SP pack build
to have the latest copy of the widget
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
JDK 1.8.0_131
N/A

Adding org.wso2.sp.solutions.http.analytics.feature

---

modules/solutions/activity-explorer/widgets/OpenTracingList/src/resources/widgetConf.json
modules/solutions/activity-explorer/widgets/OpenTracingSearch/src/resources/widgetConf.json
modules/solutions/activity-explorer/widgets/OpenTracingVisTimeline/src/resources/widgetConf.json

This PR modifies names of following Message Tracer (Activity Explorer) dashboard.
- OpenTracingList
- OpenTracingVisTimeline
- OpenTracingSearch

Modify message tracer widget names

---

modules/solutions/twitter-analytics/README.md

$subject
WSO2 SP solution documentation has the correct URL. (https://docs.wso2.com/display/SP420/Twitter+Analytics)

Fix dashboard run time URL in twitter README

---

modules/performance/extension/siddhi-execution-performance/component/pom.xml
modules/performance/extension/siddhi-execution-performance/pom.xml

Without the correct version number it is not possible for the throughput extension to be built properly.
Fix the issue of throughput extension not getting built properly.
JDK 1.8

Updating to the correct version number

---

pom.xml

> is.analytics.attempts.over.time widget is added twice, and hence there were duplicate entry in the pom file. This is to remove it.

Removing duplicate dependency entry from pom

---

modules/samples/artifacts/PublishEmailInXmlFormat/PublishEmailInXmlFormat.siddhi

>The instruction in the sample "PublishEmailInXmlFormat" needs to be edited
> In the instruction as it is stated under viewing the result is different from the actual email(output) received.
> Existing Instruction 
>Updated Instruction

Sample(PublishEmailInXmlFormat) instruction correction

---

modules/samples/artifacts/ReceiveKafkaInBinaryFormat/ReceiveKafkaInBinaryFormat.siddhi

> Fixing the naming errors in the description of the sample siddhi application 'ReceiveKafkaInBinaryFormat'.
> The fault name 'ReceiveKafkaInTextFormatWithCustomMapping' replaced with 'ReceiveKafkaInBinaryFormat'.

Fix siddhi sample app naming error in the describtion.

---

modules/samples/artifacts/PublishJmsInKeyvalueFormat/PublishJmsInKeyvalueFormat.siddhi
modules/samples/artifacts/PublishJmsInXmlFormat/PublishJmsInXmlFormat.siddhi

>Removing the quote escaping issues in the curl test commands provided for sample Siddhi applications.
>Using same type of quotes inside the curl's data field.

Fixes quote escaping issues in the sample siddhi app's curl test.

---

modules/samples/artifacts/AggregateDataIncrementally/AggregateDataIncrementally.siddhi

$subject. 
When though sample inputs read aggregation data into LowProductionStream, no condition are checked when reading data. Here, only the aggregated data is read, this should be RawMaterialStatStream
Fixes https://github.com/wso2/product-sp/issues/825
N/A

Improve AggregateDataIncrementally sample

---

modules/distribution/carbon-home/conf/worker/deployment.yaml

WSO2_CARBON_DB datasource in the configs was only used for carbon coordination in configs in HA mode by default. This can be renamed to above for higher maintainability.
1. Following to be updated that WSO2_CLUSTER_DB already defined, however, to ensure it points to only one DB in both nodes, if the nodes are in 2 different hosts. (Step 2 d)
https://docs.wso2.com/display/SP400/Minimum+High+Availability+%28HA%29+Deployment
2. Sample value to be updated 
https://docs.wso2.com/display/SP430/Configuring+Cluster+Coordination
3. The default value to be updated in HA mode
https://docs.wso2.com/display/SP430/Configuring+Datasources …

Rename WSO2_CARBON_DB to WSO2_CLUSTER_DB by default in Worker profile

---

modules/samples/artifacts/CDCSample/CDCWithListeningMode.siddhi
modules/samples/artifacts/CDCSample/CDCWithPollingMode.siddhi
pom.xml

> Adding a siddhi sample to demonstrate polling mode of cdc source.

Add Siddhi sample for CDC polling mode

---

modules/samples/artifacts/PublishHl7InEr7Format/PublishHl7InER7Format.siddhi
modules/samples/artifacts/PublishHl7InXmlFormat/PublishHl7InXmlFormat.siddhi
modules/samples/artifacts/ReceiveHl7InEr7Format/ReceiveHl7InER7Format.siddhi
modules/samples/artifacts/ReceiveHl7InXmlFormat/ReceiveHl7InXmlFormat.siddhi

The samples with instructions of how to publish and receive events using siddhi-io-hl7 for ER7 and XML format messages.
To easy to understand how hl7 works with siddhi.
Samples related to publish hl7 message to hl7 server and receive hl7 messages from the hl7 client using HAPI Test panel.

added samples for siddhi-io-hl7

---

modules/samples/artifacts/PublishEventsToPubSub/PublishGooglePubSubMessagesInTextFormat.siddhi
modules/samples/artifacts/ReceivePubSubEvents/ReceiveGooglePubSubMessagesInTextFormat.siddhi

> The samples with instructions of how to publish a message to a googlepubsub topic and how to consume a message from a googlepubsub topic that is published to the particular topic.
> To easify the task of using the connector to exchange messages reliably, quickly and asynchonously using this connector.
> Samples related to publishing a message to the googlepubsub server and receive messages from googlepubsub server.

Add samples for Google Pub/Sub

---

modules/samples/artifacts/HelloKafka/HelloKafka.siddhi
modules/samples/artifacts/HelloKafka/kafka_sample.txt
modules/samples/sample-clients/kafka-consumer/src/main/java/org/wso2/sp/sample/kafka/consumer/KafkaReceiver.java

> The previous HelloKafka sample used LowProductionAlertStream but it was a mere passthrough filter without any logic for alert generation.
add "TotalStream" I calculate the total weight produced in batches of three
generate an alert if the weight of a batch is less than 10kg.
> make HelloKafka sample more meaningful by writing Siddhi query that has logic for low production alert generation
> make the sample easy to understand by adding explanatory comments
- Ran FindSecurityBugs plugin and verified report? no

Polish HelloKafka sample to be more meaningful

---

modules/distribution/pom.xml
pom.xml

> Health Check API to check whether Server is healthy or not. It is a simple HTTP, GET api service. There is no any credentials required to access this service.
```
curl -k -X GET http://localhost:9090/health
```
> Refer API details in https://github.com/wso2/carbon-analytics/blob/master/components/org.wso2.carbon.health.check.core/src/main/resources/health-check-rest-api.yaml

Add Health Check API related features to distribution
